### ISSUE TITLE
Plays HeavySkirtMovement in the main menus.

### ISSUE THREAD

**Issue by HellishINC** [Nemoder/qtsense#1]
During world creation, embark and main menu, "28301__HerbertBoland__HeavySkirtMovementX.mp3" plays endlessly. Occurs with a empty/new gamelog.txt as well as a previously populated file.

log: http://pastebin.com/zPJj5ZEi

Fortress mode seems to work without issues. Have not tried adventure mode.

Using 43.03 + qtsense 1.6 win.

**Comment by Nemoder** [comment]
oops.  the default CurrentSeason=0 was not pointing to the first season.  It should default to winter now if it can't find what season it is.
